# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-23 18:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0002_auto_20170422_2337'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='visits',
            new_name='views',
        ),
    ]
